### PR TITLE
Fix the label display for a selection item

### LINKED ISSUE #327: Habdroid always appends item state in label
Opening an issue based on the discussion [here](https://community.openhab.org/t/remove-item-state-from-a-label/31115/5).

It appears that habdroid does not respect the item or sitemap label and will always append item state.  If you put a [] in your sitemap or item label, habdroid will no longer append the state but you end up with [] in your label text.

Example:

Items:
`Number Thermostats_Downstairs_System_Mode "System Mode" { channel="omnilink:thermostat:home:downstairs:system_mode" }
`
Sitemap:
`Selection item=Thermostats_Downstairs_System_Mode mappings=[0="Off",1="Heat",2="Cool",3="Auto",4="Emergency Heat"]`

This should just render a label that says "System Mode", but habdroid appends the state:
image

### PR DESCRIPTION
**Pull request by lolodomo**
Fixes #327

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java [hunk 1]
```diff
@@ -579,8 +579,14 @@ public void onStopTrackingTouch(SeekBar seekBar) {
                 break;
             case TYPE_SELECTION:
                 int spinnerSelectedIndex = -1;
-                if (labelTextView != null)
-                    labelTextView.setText(openHABWidget.getLabel());
+                splitString = openHABWidget.getLabel().split("\\[|\\]");
```
Comment (mueller-ma) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java]: Shouldn't it be `String[] splitString = ...`

Comment (lolodomo) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java]: No because the variable is declared globally and used in several cases of the switch.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABWidgetAdapter.java]: ok, thats in line 115

**Comment by mueller-ma** [comment]
Can I have square brackets inside the label?

**Comment by lolodomo** [comment]
@mueller-ma : I don't understand your suggestion !
The object of this PR is to suppress the display of the state value surrounded by the brackets in the displayed label at left because we already have the value displayed in the selection list at right.
Please take a look to the issue 327 for the description.

**Comment by lolodomo** [comment]
@mueller-ma : ok I see what you mean, you are talking about the title in the opened dialog box. I am fixing that.

**Comment by lolodomo** [comment]
I will need your help because I don't find where this title is set in the sub-windows.

**Comment by lolodomo** [comment]
One interesting point is that I don't have this title in the branch in which I implemented the support for image data. So there was a very very recent merge that added this title in the selection box.

**Comment by lolodomo** [comment]
Ok, it was added by you in PR #393 :-)

**Comment by lolodomo** [comment]
Ok, that is fixed now.
